"""empty message

Revision ID: 4e9bac3c8f89
Revises: None
Create Date: 2016-08-03 14:28:10.451211

"""

# revision identifiers, used by Alembic.
revision = '4e9bac3c8f89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    ### end Alembic commands ###
